default_language_version:
    python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
        args:
        - --unsafe
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args:
        - --fix
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.7.0"
    hooks:
      - id: mypy
        additional_dependencies: []
  - repo: local
    hooks:
      - id: checkpyproject
        name: poetry check
        language: system
        files: pyproject.toml
        pass_filenames: False
        entry: poetry check
      - id: requirements
        name: export requirements
        language: system
        files: poetry.lock
        pass_filenames: False
        entry: poetry export -f requirements.txt --without-hashes -o requirements.txt
      - id: requirements-test
        name: export requirements-test
        language: system
        files: poetry.lock
        pass_filenames: False
        entry: poetry export -f requirements.txt --without-hashes --dev -o requirements-test.txt
